// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIupmAvLG0lmLNGYUoztPKJHU5GXh5YiY',
    appId: '1:764247533458:web:31658741a5ae1f49a5034b',
    messagingSenderId: '764247533458',
    projectId: 'velo-pp',
    authDomain: 'velo-pp.firebaseapp.com',
    databaseURL: 'https://velo-pp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-pp.firebasestorage.app',
    measurementId: 'G-J4D2LE8M08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvm_2NqXp4tIYLFy6OuwWvU0BM5n1jtxk',
    appId: '1:764247533458:android:a10d4802303df065a5034b',
    messagingSenderId: '764247533458',
    projectId: 'velo-pp',
    databaseURL: 'https://velo-pp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-pp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgt8zjQez5YEQPIwFbZ4MvLG6k0yYXpQA',
    appId: '1:764247533458:ios:36766c020c93c9e1a5034b',
    messagingSenderId: '764247533458',
    projectId: 'velo-pp',
    databaseURL: 'https://velo-pp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-pp.firebasestorage.app',
    iosBundleId: 'com.example.veloPp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgt8zjQez5YEQPIwFbZ4MvLG6k0yYXpQA',
    appId: '1:764247533458:ios:36766c020c93c9e1a5034b',
    messagingSenderId: '764247533458',
    projectId: 'velo-pp',
    databaseURL: 'https://velo-pp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-pp.firebasestorage.app',
    iosBundleId: 'com.example.veloPp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIupmAvLG0lmLNGYUoztPKJHU5GXh5YiY',
    appId: '1:764247533458:web:eb8a6f9a5850427ca5034b',
    messagingSenderId: '764247533458',
    projectId: 'velo-pp',
    authDomain: 'velo-pp.firebaseapp.com',
    databaseURL: 'https://velo-pp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-pp.firebasestorage.app',
    measurementId: 'G-HTTVV8XN9F',
  );
}
